---
- name: Create a directory for downloading Anki
  file:
    path: '{{ anki_download_directory_path }}'
    state: directory

- name: Download and unarchive Anki
  unarchive:
    remote_src: true
    src: '{{ anki_download_url }}'
    dest: '{{ anki_download_directory_path }}'

- name: Install Anki
  become: true
  make:
    chdir: '{{ anki_download_directory_path }}/{{ anki_archive_name }}'
    target: install

- name: Delete the Anki installation directory
  file:
    path: '{{ anki_download_directory_path }}'
    state: absent
