---
- name: Install LaTeX
  become: true
  apt:
    name: texlive-full
    state: present

- import_tasks: anki.yml

- name: Install Mathpix Snipping Tool
  become: true
  snap:
    name: mathpix-snipping-tool
    state: present
