---
- name: Install Visual Studio Code
  become: true
  become_user: '{{ user_name }}'
  homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install an updated version of nano
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name: nano
    state: present
