---
- name: Tap the Homebrew emacs-plus repository
  become: true
  become_user: '{{ user_name }}'
  homebrew_tap:
    name: d12frosted/emacs-plus
    state: present

- name: Install emacs-plus
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name: emacs-plus
    state: present

- name: Clone the Spacemacs repository
  become: true
  become_user: '{{ user_name }}'
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d

- name: Tap the Homebrew cask of fonts
  become: true
  become_user: '{{ user_name }}'
  homebrew_tap:
    name: caskroom/fonts
    state: present

- name: Install Source Code Pro font
  become: true
  become_user: '{{ user_name }}'
  homebrew_cask:
    name: font-source-code-pro
    state: present
