---
- name: Add the Visual Studio Code signing key
  become: true
  apt_key:
    url: '{{ microsoft_signing_key_url }}'
    keyring: '{{ apt_keys_directory_path }}/microsoft.gpg.gpg'
    state: present

- name: Add the Visual Studio Code repository
  become: true
  apt_repository:
    repo: '{{ vscode_repository }}'
    filename: vscode
    state: present

- name: Install Visual Studio Code
  become: true
  apt:
    name:
      - code
      - apt-transport-https
    state: present
    update_cache: true
