---
- name: Update repositories
  become: true
  apt:
    update_cache: true
  changed_when: false

- name: Upgrade packages
  become: true
  apt:
    upgrade: dist

- name: Install packages
  become: true
  apt:
    name: '{{ packages }}'
    state: latest
  vars:
    packages:
      - git
