---
- name: Add git repository signing key
  become: true
  apt_key:
    keyserver: '{{ubuntu_key_server}}'
    id: '{{git_signing_key_id}}'
    keyring: /etc/apt/trusted.gpg.d/git.gpg
    state: present

- name: Add git repository
  become: true
  apt_repository:
    repo: '{{git_repository}}'
    filename: git
    state: present

- name: Update repositories
  become: true
  apt:
    update_cache: true
  changed_when: false

- name: Upgrade packages
  become: true
  apt:
    upgrade: dist

- name: Install packages
  become: true
  apt:
    name: '{{packages}}'
    state: present
  vars:
    packages:
      - git
      - snapd
