---
- name: Add VirtualBox repository signing key
  become: true
  apt_key:
    url: '{{virtualbox_repository_signing_key_url}}'
    state: present

- name: Add repositories
  become: true
  apt_repository:
    repo: '{{item}}'
    state: present
  loop:
    - ppa:git-core/ppa
    - '{{virtualbox_repository}}'

- name: Update repositories
  become: true
  apt:
    update_cache: true
  changed_when: false

- name: Upgrade packages
  become: true
  apt:
    upgrade: dist

- name: Install GNOME for virtual machine
  become: true
  apt:
    name: ubuntu-desktop
    state: present
  when: lookup('env', 'LOGNAME') == 'vagrant'

- name: Install packages
  become: true
  apt:
    name: '{{packages}}'
    state: present
  vars:
    packages:
      - anki
      - git
      - snapd
      - virtualbox-{{virtualbox_version}}

- name: Install .deb packages
  become: true
  apt:
    deb: '{{vagrant_deb_url}}'

- name: Install Vagrant vbguest plugin
  command: vagrant plugin install vagrant-vbguest
