---
- name: Update repositories
  become: yes
  apt:
    update_cache: yes
  changed_when: no

- name: Upgrade packages
  become: yes
  apt:
    upgrade: dist

- name: Install packages
  become: yes
  apt:
    name: '{{ packages }}'
    state: latest
  vars:
    packages:
      - git
