---
- name: Update repositories
  become: true
  apt:
    update_cache: true
  changed_when: false

- name: Upgrade packages
  become: true
  apt:
    upgrade: dist

- name: Install GNOME for virtual machine
  become: true
  apt:
    name: ubuntu-desktop
    state: present
  when: lookup('env', 'LOGNAME') == 'vagrant'

- name: Install packages
  become: true
  apt:
    name: '{{packages}}'
    state: present
  vars:
    packages:
      - anki
      - git
      - snapd
      - vagrant
      - virtualbox
