---
- name: Add git signing key
  become: true
  apt_key:
    keyserver: '{{ubuntu_key_server}}'
    id: '{{git_signing_key_id}}'
    keyring: '{{apt_keys_directory_path}}/git.gpg'
    state: present

- name: Add signing keys from URLs
  become: true
  apt_key:
    url: '{{item.url}}'
    keyring: '{{item.keyring}}'
    state: present
  loop:
    - url: '{{brave_signing_key_url}}'
      keyring: '{{apt_keys_directory_path}}/brave.gpg'
    - url: '{{dbeaver_signing_key_url}}'
      keyring: '{{apt_keys_directory_path}}/dbeaver.gpg'
    - url: '{{docker_signing_key_url}}'
      keyring: '{{apt_keys_directory_path}}/docker.gpg'
    - url: '{{microsoft_signing_key_url}}'
      keyring: '{{apt_keys_directory_path}}/microsoft.gpg'

- name: Add repositories
  become: true
  apt_repository:
    repo: '{{item.repo}}'
    filename: '{{item.filename}}'
    state: present
  loop:
    - repo: '{{brave_repository}}'
      filename: brave
    - repo: '{{dbeaver_repository}}'
      filename: dbeaver
    - repo: '{{docker_repository}}'
      filename: docker
    - repo: '{{git_repository}}'
      filename: git
    - repo: '{{vscode_repository}}'
      filename: vscode

- name: Update repositories
  become: true
  apt:
    update_cache: true
  changed_when: false

- name: Upgrade packages
  become: true
  apt:
    upgrade: dist

- name: Install packages
  become: true
  apt:
    name:
      - brave-browser
      - code
      - dbeaver-ce
      - docker-ce
      - git
      - snapd
      - texlive-full
    state: present

- name: Install snaps
  become: true
  command: snap install {{item}}
  loop:
    - spotify
    - vlc
