---
- name: Add git signing key
  become: true
  apt_key:
    keyserver: '{{ubuntu_key_server}}'
    id: '{{git_signing_key_id}}'
    keyring: /etc/apt/trusted.gpg.d/git.gpg
    state: present

- name: Add Microsoft signing key
  become: true
  apt_key:
    url: '{{microsoft_signing_key_url}}'
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    state: present

- name: Add repositories
  become: true
  apt_repository:
    repo: '{{item.repo}}'
    filename: '{{item.filename}}'
    state: present
  loop:
    - repo: '{{git_repository}}'
      filename: git
    - repo: '{{vscode_repository}}'
      filename: vscode

- name: Update repositories
  become: true
  apt:
    update_cache: true
  changed_when: false

- name: Upgrade packages
  become: true
  apt:
    upgrade: dist

- name: Install packages
  become: true
  apt:
    name: '{{packages}}'
    state: present
  vars:
    packages:
      - code
      - git
      - snapd
