---
- name: Install python-psutil package required by Ansible dconf module
  become: true
  apt:
    name: python-psutil
    state: present

- name: Update GNOME dconf settings
  become: true
  become_user: '{{user}}'
  dconf:
    key: '{{item.key}}'
    value: '{{item.value}}'
  loop:
    - key: /org/gnome/desktop/privacy/old-files-age
      value: uint32 7
    - key: /org/gnome/desktop/privacy/remove-old-trash-files
      value: 'true'
    - key: /org/gnome/desktop/privacy/report-technical-problems
      value: 'false'
