---
- name: Install python-psutil package required by Ansible dconf module
  become: true
  apt:
    name: python-psutil
    state: present

- name: Update GNOME dconf settings
  become: true
  become_user: '{{user}}'
  dconf:
    key: '{{item.key}}'
    value: '{{item.value}}'
  loop:
    - key: /org/gnome/desktop/calendar/show-weekdate
      value: 'true'
    - key: /org/gnome/desktop/datetime/automatic-timezone
      value: 'true'
    - key: /org/gnome/desktop/interface/clock-show-date
      value: 'true'
    - key: /org/gnome/desktop/interface/show-battery-percentage
      value: 'true'
    - key: /org/gnome/desktop/notifications/show-in-lock-screen
      value: 'false'
    - key: /org/gnome/desktop/privacy/old-files-age
      value: uint32 7
    - key: /org/gnome/desktop/privacy/remember-recent-files
      value: 'false'
    - key: /org/gnome/desktop/privacy/remove-old-trash-files
      value: 'true'
    - key: /org/gnome/desktop/privacy/report-technical-problems
      value: 'false'
    - key: /org/gnome/desktop/privacy/send-software-usage-stats
      value: 'false'
    - key: /org/gnome/desktop/search-providers/disabled
      value:
        - 'org.gnome.Terminal.desktop'
        - 'seahorse.desktop'
        - 'gnome-control-center.desktop'
    - key: /org/gnome/desktop/wm/preferences/num-workspaces
      value: 1
    - key: /org/gnome/mutter/dynamic-workspaces
      value: 'false'
    - key: /org/gnome/nautilus/desktop/trash-icon-visible
      value: 'false'
    - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
      value: 'true'
    - key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic
      value: 'false'
    - key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-from
      value: 20.5
    - key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-to
      value: 6
    - key: /org/gnome/settings-daemon/plugins/power/idle-dim
      value: 'false'
    - key: /org/gnome/shell/disable-user-extensions
      value: 'true'
    - key: /org/gnome/shell/favorite-apps
      value:
        - 'org.gnome.Nautilus.desktop'
        - 'brave-browser.desktop'
        - 'code.desktop'
        - 'org.gnome.Terminal.desktop'
        - 'dbeaver.desktop'
        - 'virtualbox.desktop'
        - 'spotify_spotify.desktop'
    - key: /org/gnome/terminal/legacy/default-show-menubar
      value: 'false'
