---
- name: Update GNOME dconf settings
  dconf:
    key: '{{item.key}}'
    value: '{{item.value}}'
  loop:
    - key: /org/gnome/desktop/privacy/remove-old-trash-files
      value: 'true'
    - key: /org/gnome/desktop/privacy/report-technical-problems
      value: 'false'
