---
- name: Create ansible user
  user:
    name: ansible
    uid: 900

- name: Copy sudoers_ansible
  become: true
  copy:
    src: files/sudoers-ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
