---
- name: Create {{user}} user
  become: true
  user:
    name: '{{user}}'
    groups: sudo
    # justinas
    password: $6$mysecretsalt$u.SLHFJRv7zzTUMz.Qlz3tIqqh/An4KUOp49QYGqZWccadwYfOKT6T7ptHy8Gm4iPlfNUMEJAOsFPierEBE7z/
    update_password: on_create

- name: Create ansible user
  become: true
  user:
    name: ansible
    uid: 900

- name: Copy sudoers_ansible
  become: true
  copy:
    src: files/sudoers-ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
