---
- name: Add VirtualBox signing key
  become: true
  apt_key:
    url: '{{virtualbox_signing_key_url}}'
    keyring: '{{apt_keys_directory_path}}/virtualbox.gpg'
    state: present

- name: Add VirtualBox repository
  become: true
  apt_repository:
    repo: '{{virtualbox_repository}}'
    filename: virtualbox
    state: present
    update_cache: true

- name: Install VirtualBox
  become: true
  apt:
    name: virtualbox-{{virtualbox_version}}
    state: present

- name: Install Vagrant
  become: true
  apt:
    deb: '{{vagrant_deb_url}}'

- name: Install Vagrant vbguest plugin
  command: vagrant plugin install vagrant-vbguest

- name: Install NFS server to support Vagrant synced folders backed by NFS
  become: true
  apt:
    name: nfs-kernel-server
    state: present

- name: Enable passwordless NFS configuration
  become: true
  copy:
    src: files/sudoers-vagrant-synced-folders
    dest: /etc/sudoers.d/vagrant-synced-folders
    owner: root
    group: root
    mode: 0440
