---
- name: Add VirtualBox signing key
  become: true
  apt_key:
    url: '{{virtualbox_signing_key_url}}'
    keyring: '{{apt_keys_directory_path}}/virtualbox.gpg'
    state: present

- name: Add VirtualBox repository
  become: true
  apt_repository:
    repo: '{{virtualbox_repository}}'
    filename: virtualbox
    state: present
    update_cache: true

- name: Install VirtualBox
  become: true
  apt:
    name: virtualbox-{{virtualbox_version}}
    state: present

- name: Install Vagrant
  become: true
  apt:
    deb: '{{vagrant_deb_url}}'

- name: Install Vagrant vbguest plugin
  command: vagrant plugin install vagrant-vbguest
