---
- name: Create a directory for a wallpaper
  become: true
  become_user: '{{ user_name }}'
  file:
    path: '{{ wallpaper_directory_path }}'
    state: directory

- name: Download a wallpaper
  become: true
  become_user: '{{ user_name }}'
  get_url:
    url: '{{ wallpaper_url }}'
    dest: '{{ wallpaper_directory_path }}/{{ wallpaper_file_name }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0600

- name: Set the wallpaper
  become: true
  become_user: '{{ user_name }}'
  dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file://{{ wallpaper_directory_path }}/{{ wallpaper_file_name }}'"
