---
- name: Upgrade installed packages
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install Yay
  import_tasks: yay.yml

- name: Install Ansible AUR helper
  command: yay --sync --noconfirm ansible-aur-git
