---
- name: Check if Anaconda is installed
  stat:
    path: '{{ anaconda_installation_directory }}/bin/conda'
  changed_when: false
  register: anaconda_conda_binary

- name: Install Anaconda
  when: not anaconda_conda_binary.stat.exists
  block:
    - name: Install Anaconda extended dependencies
      become: true
      apt:
        name:
          - libgl1-mesa-glx
          - libegl1-mesa
          - libxrandr2
          - libxrandr2
          - libxss1
          - libxcursor1
          - libxcomposite1
          - libasound2
          - libxi6
          - libxtst6
        state: present

    - name: Download the Anaconda installer
      become: true
      become_user: '{{ user_name }}'
      get_url:
        url: '{{ anaconda_download_url }}'
        dest: '{{ anaconda_download_directory_path }}/{{ anaconda_installer_name }}'
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        timeout: 600
        mode: 0700

    - name: Run the Anaconda installer
      become: true
      become_user: '{{ user_name }}'
      command: >-
        bash {{ anaconda_download_directory_path }}/{{ anaconda_installer_name }}
        -b -p {{ anaconda_installation_directory }}

    - name: Delete the Anaconda installer
      become: true
      become_user: '{{ user_name }}'
      file:
        path: '{{ anaconda_download_directory_path }}/{{ anaconda_installer_name }}'
        state: absent

    - name: Install conda’s shell functions
      become: true
      become_user: '{{ user_name }}'
      shell: >-
        eval "$({{ anaconda_installation_directory }}/bin/conda shell.bash hook)" &&
        conda init
