---
- name: Install nvm
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name: nvm
    state: present

- name: Create nvm’s working directory
  become: true
  become_user: '{{ user_name }}'
  file:
    path: ~/.nvm
    state: directory

- name: Install Node.js
  become: true
  become_user: '{{ user_name }}'
  shell: . /usr/local/opt/nvm/nvm.sh && nvm install --lts && nvm use --lts
