---
- name: Install pyenv and Python build dependencies
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name:
      - openssl
      - pyenv
      - pyenv-virtualenv
      - readline
      - sqlite3
      - xz
      - zlib
    state: present

- name: Install additional SDK headers
  become: true
  command: >-
     installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

- name: Install the needed Python versions
  become: true
  become_user: '{{ user_name }}'
  # The additional variables before the pyenv command are necessary here to
  # prevent the error: “ImportError: No module named pyexpat”.
  # See: https://github.com/pyenv/pyenv/issues/1066
  shell: >-
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
    MACOSX_DEPLOYMENT_TARGET=10.14 pyenv install {{ item }}
  register: pyenv_install_result
  failed_when: >-
    pyenv_install_result.rc != 0 and
    pyenv_install_result.stderr_lines != ["pyenv: /Users/justinas/.pyenv/versions/" + item + " already exists"]
  loop: '{{ pyenv_python_versions }}'

- name: Set global versions of Python to be used in all shells
  become: true
  become_user: '{{ user_name }}'
  command: pyenv global {{ pyenv_python_versions | join(" ") }}

- name: Rehash shims
  become: true
  become_user: '{{ user_name }}'
  command: pyenv rehash

- name: Update pip for each Python version
  become: true
  become_user: '{{ user_name }}'
  pip:
    name: pip
    state: latest
    executable: ~/.pyenv/versions/{{ item }}/bin/pip
  loop: '{{ pyenv_python_versions }}'
