---
- name: Install Vagrant
  become: true
  apt:
    deb: '{{ vagrant_deb_url }}'
    state: present

- name: Install the Vagrant vbguest plugin
  become: true
  become_user: '{{ user_name }}'
  command: vagrant plugin install vagrant-vbguest

- name: Install a NFS server to support the Vagrant synced folders backed by NFS
  become: true
  apt:
    name: nfs-kernel-server
    state: present

- name: Enable passwordless NFS configuration
  become: true
  copy:
    src: files/vagrant-synced-folders
    dest: /etc/sudoers.d/vagrant-synced-folders
    owner: root
    group: root
    mode: 0440
